name: Openwrt Build Bot
on:
  push:
    branches: main
  #schedule:
  #- cron: 0 0 * * 1
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
jobs:
  buildimg:
    name: Build Openwrt Image
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@master
    - name: System update
      run: |
        sudo apt-get update
        sudo apt-get -y install gcc g++ unzip make libncurses-dev mkisofs
        sudo apt-get -y install tmux tmate
        sudo apt-get -y dist-upgrade
    - name: Configure SSH
      run: |
        sudo mkdir -p ~/.ssh
        sudo ssh-keygen -t rsa -P "" -f ~/.ssh/id_rsa
    - name: Run Tmate
      run: |
        tmate
